spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        # any online food app (AuthFilter created inside gateway to validate the user)
        - id: food-app
          uri: lb://FOOD-APP
          predicates:
            - Path=/food/**
          filters:
            - AuthFilter

        # restaurant service (AuthFilter created inside gateway to validate the user)
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**
          filters:
            - AuthFilter

        # service registry
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**

auth:
  token:
    jwtSecret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/